# Generated by Django 4.2.11 on 2024-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applying_hiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='job_doc',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
